-- MySQL Script generated by MySQL Workbench
-- Mon Dec 22 14:42:47 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `nama` VARCHAR(16) NOT NULL,
  `noTlp` INT NOT NULL,
  `idUser` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idUser`));


-- -----------------------------------------------------
-- Table `mydb`.`vendor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendor` (
  `Nama` VARCHAR(16) NOT NULL,
  `NoTlp` INT NOT NULL,
  `idVendor` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idVendor`));


-- -----------------------------------------------------
-- Table `mydb`.`pariwisata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pariwisata` (
  `noTlp` INT NOT NULL,
  `nama` VARCHAR(255) NOT NULL,
  `alamat` VARCHAR(32) NOT NULL,
  `hargaTm` INT NOT NULL,
  `idPariwisata` VARCHAR(15) NOT NULL,
  `tourGuide` TINYINT NULL,
  `user_idUser` VARCHAR(15) NOT NULL,
  `vendor_idVendor` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPariwisata`, `user_idUser`, `vendor_idVendor`),
  INDEX `fk_pariwisata_user1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_pariwisata_vendor1_idx` (`vendor_idVendor` ASC) VISIBLE,
  CONSTRAINT `fk_pariwisata_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pariwisata_vendor1`
    FOREIGN KEY (`vendor_idVendor`)
    REFERENCES `mydb`.`vendor` (`idVendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`penginapan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`penginapan` (
  `nama` VARCHAR(16) NOT NULL,
  `alamat` VARCHAR(255) NOT NULL,
  `noTlp` INT NOT NULL,
  `idPeng` VARCHAR(15) NOT NULL,
  `vendor_idVendor` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idPeng`, `vendor_idVendor`),
  INDEX `fk_penginapan_vendor1_idx` (`vendor_idVendor` ASC) VISIBLE,
  CONSTRAINT `fk_penginapan_vendor1`
    FOREIGN KEY (`vendor_idVendor`)
    REFERENCES `mydb`.`vendor` (`idVendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`kamar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`kamar` (
  `harga` INT NOT NULL,
  `tipeKmr` VARCHAR(255) NOT NULL,
  `idKmr` VARCHAR(15) NOT NULL,
  `user_idUser` VARCHAR(15) NOT NULL,
  `penginapan_idPeng` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idKmr`, `user_idUser`, `penginapan_idPeng`),
  INDEX `fk_kamar_user1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_kamar_penginapan1_idx` (`penginapan_idPeng` ASC) VISIBLE,
  CONSTRAINT `fk_kamar_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_kamar_penginapan1`
    FOREIGN KEY (`penginapan_idPeng`)
    REFERENCES `mydb`.`penginapan` (`idPeng`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`transportasi`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`transportasi` (
  `namaRental` VARCHAR(20) NOT NULL,
  `harga` INT NOT NULL,
  `alamat` VARCHAR(32) NOT NULL,
  `idTransport` VARCHAR(15) NOT NULL,
  `user_idUser` VARCHAR(15) NOT NULL,
  `vendor_idVendor` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idTransport`, `user_idUser`, `vendor_idVendor`),
  INDEX `fk_transportasi_user1_idx` (`user_idUser` ASC) VISIBLE,
  INDEX `fk_transportasi_vendor1_idx` (`vendor_idVendor` ASC) VISIBLE,
  CONSTRAINT `fk_transportasi_user1`
    FOREIGN KEY (`user_idUser`)
    REFERENCES `mydb`.`user` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_transportasi_vendor1`
    FOREIGN KEY (`vendor_idVendor`)
    REFERENCES `mydb`.`vendor` (`idVendor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
